import test from 'node:test';import assert from 'node:assert/strict';import {adaptRequest,adaptResponse} from '../public/protocol.mjs';
const tools=[{type:'function',function:{name:'read_file',description:'Read a file',parameters:{type:'object',properties:{path:{type:'string'},limit:{type:'integer'},flags:{type:'array',items:{type:'boolean'}}},required:['path'],additionalProperties:false}}}];
const req={messages:[{role:'user',content:'Read /tmp/a'}],tools};
const xml=(body,name='read_file')=>`<tool_call>\n<function=${name}>\n${body}</function>\n</tool_call>`;
const param=(k,v)=>`<parameter=${k}>\n${v}\n</parameter>\n`;
const raw=(content,finish_reason='stop')=>({choices:[{message:{role:'assistant',content},finish_reason}]});
test('native tool schema/instructions added without native WebLLM tools',()=>{const r=adaptRequest(req);assert.match(r.messages[0].content,/<tools>/);assert.match(r.messages[0].content,/read_file/);assert.equal(r.tools,undefined);assert.equal(r.messages[1].content,'Read /tmp/a');});
test('typed complete call becomes OpenAI call; regular answer allowed',()=>{const r=adaptResponse(raw(xml(param('path',' /tmp/a\nb ')+param('limit','2')+param('flags','[true,false]'))),req);assert.deepEqual(JSON.parse(r.choices[0].message.tool_calls[0].function.arguments),{path:' /tmp/a\nb ',limit:2,flags:[true,false]});assert.equal(r.choices[0].finish_reason,'tool_calls');assert.equal(adaptResponse(raw('Hello'),req).choices[0].message.content,'Hello');});
test('tool result and second turn preserve actual historical calls',()=>{const call=adaptResponse(raw(xml(param('path','/tmp/a'))),req).choices[0].message;const r=adaptRequest({...req,messages:[...req.messages,call,{role:'tool',tool_call_id:call.tool_calls[0].id,content:'secret=42'}]},16384,'Qwen3.5-4B-q4f32_1-MLC');assert.match(r.messages[2].content,/<function=read_file>/);assert.deepEqual(r.messages[3],{role:'user',content:'<tool_response>\nsecret=42\n</tool_response>'});});
test('unknown tools, malformed and truncated calls never execute',()=>{for(const s of [xml(param('path','a'),'missing'),xml(param('path','a')+param('path','b')),xml(param('path','a'))+' trailing','<tool_call>broken'])assert.throws(()=>adaptResponse(raw(s),req));assert.throws(()=>adaptResponse(raw(xml(param('path','a')),'length'),req),/Truncated/);});
test('none, required, named choice and parallel flag are enforced',()=>{assert.doesNotMatch(adaptRequest({...req,tool_choice:'none'}).messages[0].content,/<tools>/);assert.throws(()=>adaptResponse(raw(xml(param('path','a'))),{...req,tool_choice:'none'}));assert.throws(()=>adaptResponse(raw('hi'),{...req,tool_choice:'required'}));assert.throws(()=>adaptRequest({...req,tool_choice:{type:'function',function:{name:'missing'}}}));assert.throws(()=>adaptResponse(raw(xml(param('path','a'))+xml(param('path','b'))),{...req,parallel_tool_calls:false}));});

test('argument validation belongs to CLI, including unknown command parameter',()=>{const r=adaptResponse(raw(xml(param('command','ls -la')+param('limit','oops'))),req);assert.deepEqual(JSON.parse(r.choices[0].message.tool_calls[0].function.arguments),{command:'ls -la',limit:'oops'});});
