import {connect} from './shared-connect.mjs';import {sendCLI} from './cli-input.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import path from 'node:path';
const dir='evidence/tutorial-web';await fs.mkdir(dir,{recursive:true});const b=await connect(),p=await b.contexts()[0].newPage();let web;
try{
 if(process.env.LOCAL_TEST){const manifest=JSON.parse(await fs.readFile('hosting/asset-manifest.json','utf8'));await p.route('https://wasnotwas.com/browser-linux-lab/**',async r=>{const name=new URL(r.request().url()).pathname.replace('/browser-linux-lab/','')||'index.html';const mime=manifest.find(e=>e.target===name)?.mime||({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.wasm':'application/wasm'}[path.extname(name)]||'application/octet-stream');await r.fulfill({body:await fs.readFile('hosting/site/browser-linux-lab/'+name),contentType:mime,headers:{'Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin'}});});}
 await p.goto('https://wasnotwas.com/browser-linux-lab/');await p.locator('#model').selectOption(process.env.QWEN?'qwen':'simulator');await p.locator('#boot').click();await p.waitForFunction(()=>['ready','failed'].includes(document.body.dataset.phase),null,{timeout:240000});assert.equal(await p.evaluate(()=>document.body.dataset.phase),'ready',await p.locator('#status').textContent());
 await sendCLI(p,'alias tl=term-llm');await p.waitForTimeout(300);await sendCLI(p,'tl serve web --port 8081 --auth none');await p.waitForFunction(()=>lab.serial.includes('serve listening')||lab.serial.includes('Error:'),null,{timeout:90000});console.log('SERVER',await p.evaluate(()=>lab.screen));
 for(let n=0;n<10;n++)await p.locator('.lesson-nav button').last().click();
 const popup=b.contexts()[0].waitForEvent('page');await p.getByRole('button',{name:'Open web interface',exact:true}).click();web=await popup;web.on('response',async r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url(),(await r.text().catch(()=>'' )).slice(0,800));});web.on('console',m=>console.log('WEB',m.type(),m.text().slice(0,300)));web.on('pageerror',e=>console.log('WEB ERROR',e.message));
 await web.waitForURL(/guest-web/,{timeout:30000});await web.waitForLoadState('domcontentloaded',{timeout:90000});await web.locator('#promptInput').waitFor({timeout:60000});await web.locator('#promptInput').fill('What are three useful things to bring to a picnic?');await web.locator('#promptInput').press('Enter');await web.waitForFunction(()=>/blanket|cooler|water bottle/i.test(document.body.innerText),null,{timeout:120000});await p.waitForFunction(()=>lab.webResponse.includes('event: response.completed'),null,{timeout:30000});await fs.writeFile(dir+'/last-response.sse',await p.evaluate(()=>lab.webResponse));await web.waitForTimeout(1000);await web.waitForFunction(()=>document.querySelector('#sendBtn')?.getAttribute('aria-label')==='Send message',null,{timeout:30000});await web.waitForTimeout(300);await web.locator('#promptInput').fill('One person is vegetarian. Adjust your suggestions.');await web.locator('#promptInput').press('Enter');await web.waitForFunction(()=>document.querySelectorAll('.message.assistant').length>=2&&/vegetarian|meat-free/i.test([...document.querySelectorAll('.message.assistant')].at(-1).innerText),null,{timeout:120000});await web.screenshot({path:dir+'/web.png'});await fs.writeFile(dir+'/web.txt',await web.locator('body').innerText());await fs.writeFile(dir+'/terminal.txt',await p.evaluate(()=>lab.screen));console.log('WEB BODY',(await web.locator('body').innerText()).slice(0,7000));await p.waitForFunction(()=>lab.webResponse.includes('event: response.completed'),null,{timeout:30000});await fs.writeFile(dir+'/last-response.sse',await p.evaluate(()=>lab.webResponse));await web.waitForTimeout(1000);await web.waitForFunction(()=>document.querySelector('#sendBtn')?.getAttribute('aria-label')==='Send message',null,{timeout:30000});await p.locator('.xterm-helper-textarea').focus();await p.keyboard.press('Control+c');await p.waitForFunction(()=>/\/workspace#\s*$/.test(lab.screen.trimEnd()),null,{timeout:30000});await web.goto(web.url());assert.match(await web.locator('body').innerText(),/not running/);await fs.writeFile(dir+'/result-'+(process.env.QWEN?'qwen':'simulator')+'.json',JSON.stringify({mode:process.env.QWEN?'qwen':'simulator',webChat:true,followup:true,ctrlCStopsServer:true}));console.log('PASS web conversation and Ctrl+C shutdown');
}catch(e){await fs.writeFile(dir+'/failure.json',JSON.stringify({error:e.stack,webResponse:await p.evaluate(()=>window.lab?.webResponse).catch(()=>''),terminal:await p.evaluate(()=>window.lab?.screen).catch(()=>''),status:await p.locator('#status').textContent().catch(()=>''),web:web?await web.locator('body').innerText().catch(()=>''):null},null,2));throw e;}finally{await web?.close();await p.close();await b.close();}
