// End-to-end tutorial through real Ghostty keyboard input. Only static assets may
// be routed locally; all Qwen outputs, guest commands, files and MCP calls are real.
import {connect} from './shared-connect.mjs';import {sendCLI} from './cli-input.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import path from 'node:path';
const sim=process.env.SIMULATOR==='1',local=process.env.LOCAL_TEST==='1',dir=`evidence/tutorial-e2e/${local?'local':'hosted'}${sim?'-simulator':''}`;await fs.mkdir(dir,{recursive:true});
const b=await connect(),p=await b.contexts()[0].newPage();let step=0;const results=[];
const save=async(name)=>{await fs.writeFile(`${dir}/${name}.json`,JSON.stringify({events:await p.evaluate(()=>window.tutorialEvents),screen:await p.evaluate(()=>window.lab?.screen)},null,2));await p.screenshot({path:`${dir}/${name}.png`});};
async function shell(command,tag){
 await sendCLI(p,`printf "\\nCHECK_${tag}_START\\n"; ${command}; code=$?; printf "\\nCHECK_${tag}_DONE:%s\\n" "$code"`);
 await p.waitForFunction(t=>lab.serial.includes('\r\nCHECK_'+t+'_DONE:'),tag,{timeout:120000});
 const serial=await p.evaluate(()=>lab.serial),end=new RegExp('CHECK_'+tag+'_DONE:(\\d+)').exec(serial);
 assert.equal(end?.[1],'0',`${command} failed: ${serial.slice(-2500)}`);
 return serial.split('\r\nCHECK_'+tag+'_START\r\n').at(-1).split('\r\nCHECK_'+tag+'_DONE:')[0];
}
async function next(){await save(`step-${step}`);results.push({step,ok:true});await p.locator('.lesson-nav button').last().click();step++;}
async function clearEvents(){await p.evaluate(()=>tutorialEvents=[]);}
async function answer(text){await clearEvents();await sendCLI(p,text);await p.waitForFunction(()=>tutorialEvents.some(e=>e.result?.choices&&!e.result.choices[0].message.tool_calls)||tutorialEvents.some(e=>e.error),null,{timeout:90000});assert.deepEqual(await p.evaluate(()=>tutorialEvents.filter(e=>e.error)),[]);await p.waitForTimeout(500);return p.evaluate(()=>tutorialEvents.filter(e=>e.result?.choices).map(e=>e.result.choices[0].message.content).join('\n'));}
try{
 const modelRequests=[];p.on('request',r=>{if(/huggingface\.co|binary-mlc-llm-libs|inference-worker\.js|gemma-worker\.js/.test(r.url()))modelRequests.push(r.url());});
 if(sim)await p.addInitScript(()=>Object.defineProperty(Navigator.prototype,'gpu',{get:()=>undefined,configurable:true}));
 if(local){const manifest=JSON.parse(await fs.readFile('hosting/asset-manifest.json','utf8'));await p.route('https://term-llm.com/learn/**',async r=>{let name=decodeURIComponent(new URL(r.request().url()).pathname.replace('/learn/',''))||'index.html';assert.ok(!name.includes('..'));const mime=manifest.find(e=>e.target===name)?.mime||({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.wasm':'application/wasm'}[path.extname(name)]||'application/octet-stream');try{await r.fulfill({body:await fs.readFile('hosting/site/learn/'+name),contentType:mime,headers:{'Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin'}});}catch{await r.fulfill({status:404,body:'Missing staged asset '+name});}});}
 await p.addInitScript(()=>{const create=URL.createObjectURL;URL.createObjectURL=function(blob){if(blob.type==='text/plain')window.exportedChecklist=blob.text();return create.call(this,blob);};window.tutorialEvents=[];const W=Worker;window.Worker=class extends W{constructor(...a){super(...a);this.addEventListener('message',e=>{if(e.data.diagnostic||e.data.error||e.data.result)tutorialEvents.push(e.data);});}};});
 await p.setViewportSize({width:1440,height:900});await p.goto(process.env.TUTORIAL_URL||'https://term-llm.com/learn/');if(sim){await p.waitForFunction(()=>document.querySelector('#model').value==='simulator');assert.match(await p.locator('#mode-note').textContent(),/Scripted/);}await p.locator('#boot').click();await p.waitForFunction(()=>['ready','failed'].includes(document.body.dataset.phase),null,{timeout:240000});assert.equal(await p.evaluate(()=>document.body.dataset.phase),'ready',await p.locator('#status').textContent());
 assert.ok(await p.evaluate(model=>tutorialEvents.some(e=>e.result?.loaded&&e.result.model===model),sim?'tutorial-simulator':'Qwen3-8B-q4f32_1-MLC'));await fs.writeFile(dir+'/load.json',JSON.stringify(await p.evaluate(()=>tutorialEvents),null,2));step=1;
 assert.match(await shell('pwd; ls; cat notes.txt','shell'),/community hall/);await next();
 // Lesson 2: completions must be genuinely absent, then installed by the reader.
 await p.locator('#terminal textarea').focus();await p.keyboard.type('term-llm ch');await p.keyboard.press('Tab');await p.waitForTimeout(1500);assert.match(await p.evaluate(()=>lab.screen.trimEnd()),/term-llm ch$/,'the guest must not ship preconfigured term-llm completions');await p.keyboard.press('Control+c');await p.waitForTimeout(350);
 assert.match(await shell('term-llm config completion zsh --install','install-completions'),/site-functions/);
 await shell("echo 'fpath+=(~/.local/share/zsh/site-functions)' >> ~/.zshrc; echo 'autoload -Uz compinit && compinit' >> ~/.zshrc",'zshrc');
 // exec $SHELL genuinely restarts the guest shell; .zshrc runs again and re-emits LAB_READY.
 const readyCount=await p.evaluate(()=>(lab.serial.match(/LAB_READY/g)||[]).length);
 await sendCLI(p,'exec $SHELL');await p.waitForFunction(n=>(lab.serial.match(/LAB_READY/g)||[]).length>n,readyCount,{timeout:60000});await p.waitForTimeout(1200);
 assert.match(await shell('pwd','after-restart'),/\/workspace/);
 await p.keyboard.type('term-llm ch');await p.keyboard.press('Tab');await p.waitForFunction(()=>/term-llm chat\s*$/.test(lab.screen.trimEnd()),null,{timeout:15000});await p.keyboard.press('Control+c');await p.waitForTimeout(350);await next();
 // Lesson 3: the alias, and the compdef that --install cannot do for you.
 await shell('alias tl=term-llm','alias');await shell('compdef _term-llm tl','compdef');await p.keyboard.type('tl as');await p.keyboard.press('Tab');await p.waitForFunction(()=>/tl ask\s*$/.test(lab.screen.trimEnd()),null,{timeout:15000});await p.keyboard.press('Control+c');await p.waitForTimeout(350);assert.match(await shell('tl --help','help'),/chat/);await p.keyboard.press('ArrowUp');await p.waitForTimeout(200);assert.match(await p.evaluate(()=>lab.screen.trimEnd()),/tl --help/);await p.keyboard.press('Control+c');await p.waitForTimeout(350);await next();
 await clearEvents();await shell('tl ask "What are three useful things to bring to a picnic?"','ask');assert.ok(await p.evaluate(()=>tutorialEvents.some(e=>e.result?.choices?.[0]?.message?.content?.length>40)));await next();
 await shell('tl ask -f notes.txt "Summarize our picnic plan in three bullets."','file');await clearEvents();await shell('cat notes.txt | tl ask "What should we do if it rains?"','pipe');assert.match(await p.evaluate(()=>tutorialEvents.filter(e=>e.result?.choices).map(e=>e.result.choices[0].message.content).join('\n')),/community hall/i);await next();
 for(const [tag,flag]of [['print','--print-only'],['execute','']]){await clearEvents();await sendCLI(p,`tl exec ${flag} "List the files in the current directory"; printf "\\nCHECK_${tag}_DONE\\n"`);await p.waitForFunction(()=>tutorialEvents.some(e=>e.result?.choices?.[0]?.message?.tool_calls?.length),null,{timeout:90000});await p.waitForTimeout(800);await save('exec-'+tag+'-selector');await p.keyboard.press('Enter');await p.waitForFunction(t=>lab.serial.includes('\r\nCHECK_'+t+'_DONE\r\n'),tag,{timeout:30000});}await next();
 await clearEvents();await sendCLI(p,'tl ask --tools read_file "Read notes.txt and tell me our rain plan."; printf "\\nCHECK_read_DONE\\n"');await p.waitForFunction(()=>tutorialEvents.some(e=>e.result?.choices?.[0]?.message?.tool_calls?.length),null,{timeout:90000});await p.waitForFunction(()=>lab.serial.includes('\r\nCHECK_read_DONE\r\n')||/allow|approve|permission/i.test(lab.screen.split('CHECK_execute_DONE').at(-1)),null,{timeout:30000});await save('read-approval');
 // The actual prompt will be inspected; do not auto-approve arbitrary requests.

 if(!await p.evaluate(()=>lab.serial.includes('\r\nCHECK_read_DONE\r\n'))){const screen=await p.evaluate(()=>lab.screen);if(/allow|approve|permission/i.test(screen)){await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');}}
 await p.waitForFunction(()=>lab.serial.includes('\r\nCHECK_read_DONE\r\n'),null,{timeout:90000});assert.match(await p.evaluate(()=>tutorialEvents.filter(e=>e.result?.choices&&!e.result.choices[0].message.tool_calls).map(e=>e.result.choices[0].message.content).join('\n')),/community hall/i);await next();
 assert.match(await shell('tl mcp list','mcp-list'),/picnic/);assert.match(await shell('tl mcp info picnic','mcp-info'),/checklist/);assert.match(await shell('tl mcp run picnic checklist guests=4','mcp-run'),/4 guests/);assert.match(await shell('tl mcp run picnic checklist guests=6','mcp-six'),/6 guests/);await next();
 await sendCLI(p,'tl chat');await p.waitForFunction(()=>/Type a message/.test(lab.screen),null,{timeout:30000});await answer('Help me plan a picnic for four people. Suggest three foods.');const adjusted=await answer('One person is vegetarian. Adjust your suggestions.');assert.match(adjusted,/vegetarian|hummus|cheese|vegetable|veggie/i);await next();
 await sendCLI(p,'/help');await p.waitForTimeout(600);await save('chat-help');await p.keyboard.press('Escape');await p.waitForTimeout(600);await sendCLI(p,'/quit');await p.waitForFunction(()=>/\/workspace#\s*$/.test(lab.screen.trimEnd()),null,{timeout:30000});await sendCLI(p,'tl chat --resume');await p.waitForFunction(()=>/Type a message/.test(lab.screen),null,{timeout:30000});assert.match(await answer('Remind me of the dietary requirement.'),/vegetarian/i);await sendCLI(p,'/quit');await p.waitForFunction(()=>/\/workspace#\s*$/.test(lab.screen.trimEnd()),null,{timeout:30000});await next();
 assert.match(await shell('tl agents --builtin','agents'),/shell/);assert.match(await shell('tl agents show shell','agent-show'),/Shell command helper/);await clearEvents();await shell('tl ask @shell "Explain what pwd does without running it."','agent-ask');assert.match(await p.evaluate(()=>tutorialEvents.filter(e=>e.result?.choices).map(e=>e.result.choices[0].message.content).join('\n')),/working directory|current directory/i);assert.equal(await p.evaluate(()=>tutorialEvents.some(e=>e.result?.choices?.[0]?.message?.tool_calls?.length)),false);await shell('tl agents copy shell my-shell','agent-copy');assert.match(await shell('tl agents show my-shell','agent-copy-show'),/my-shell/);await next();
 await shell('tl ask --text -f notes.txt "Make a picnic checklist of at most five items." > checklist.txt','checklist');const checklist=await p.evaluate(async()=>new TextDecoder().decode(await lab.vm.read_file('workspace/checklist.txt')));assert.ok(checklist.length>30);assert.match(checklist,/sandwich|water|blanket/i);await shell('cat checklist.txt','cat');await save('step-11');results.push({step:11,ok:true,checklist});
 const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Save checklist',exact:true}).click();const download=await downloadPromise;const exported=await p.evaluate(()=>window.exportedChecklist);assert.equal(exported,checklist);assert.equal(await download.failure(),null);await fs.writeFile(dir+'/downloaded-checklist.txt',exported);await p.locator('.lesson-nav button').first().click();assert.match(await p.locator('.lesson-count').textContent(),/10 OF 12/);await p.locator('.lesson-nav button').last().click();assert.equal(await p.evaluate(async()=>new TextDecoder().decode(await lab.vm.read_file('workspace/checklist.txt'))),checklist);
 if(sim){
  await shell("printf 'If it rains, meet at the museum.\\n' > notes.txt",'change-notes');
  const changed=await shell('tl ask -f notes.txt "What should we do if it rains?"','changed-rain');assert.match(changed,/museum/);assert.doesNotMatch(changed,/community hall/);
  assert.match(await shell('tl ask "Explain quantum chromodynamics."','unsupported'),/scripted tutorial simulator, not a general AI/);
 }
 // Canned image Easter egg: actual PNG files and native Kitty graphics.
 for(const animal of ['cat','dog','elephant','rabbit','fox','owl']){
  await shell(`tl image ${animal} -o ${animal}.png`,'image-'+animal);assert.match(await p.evaluate(()=>lab.screen),/canned illustration/);
  const signature=await p.evaluate(async a=>Array.from((await lab.vm.read_file('workspace/'+a+'.png')).slice(0,8)),animal);
  assert.deepEqual(signature,[137,80,78,71,13,10,26,10]);
  await p.waitForFunction(()=>[...document.querySelectorAll('.term-images canvas')].some(c=>c.width>0&&c.height>0),null,{timeout:10000,polling:100});await save('image-'+animal);
 }
 await shell('tl image cat -o - > piped.png','image-pipe');
 assert.deepEqual(await p.evaluate(async()=>Array.from((await lab.vm.read_file('workspace/piped.png')).slice(0,8))),[137,80,78,71,13,10,26,10]);
 assert.match(await shell('tl image dinosaur; test $? -eq 2','image-unknown'),/no image model is connected/);
 // Both panes must be visible on desktop; mobile tabs must preserve access to each.
 assert.ok(await p.locator('#chat-pane').isVisible());assert.ok(await p.locator('#guide-pane').isVisible());await p.setViewportSize({width:390,height:844});await p.locator('#tab-guide').click();assert.ok(await p.locator('#lesson').isVisible());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await save('mobile-guide');await p.locator('#tab-chat').click();assert.ok(await p.locator('#terminal').isVisible());await save('mobile-terminal');await fs.writeFile(dir+'/results.json',JSON.stringify(results,null,2));if(sim){assert.deepEqual(modelRequests,[]);assert.match(await p.locator('#effective').textContent(),/SIMULATOR.*scripted/);await fs.writeFile(dir+'/network.json',JSON.stringify({webgpuExposed:await p.evaluate(()=>!!navigator.gpu),modelRequests}));}console.log('PASS FIRST ELEVEN STEPS',sim?'SIMULATOR':'QWEN',JSON.stringify(results));
}catch(e){await save('failure').catch(()=>{});await fs.writeFile(dir+'/failure.json',JSON.stringify({step,error:e.stack,completed:results},null,2));throw e;}finally{await p.close();await b.close();}
